# Generated by Django 4.0.4 on 2022-06-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_project_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricular',
            name='duration',
            field=models.DateField(),
        ),
    ]
