# Generated by Django 4.0.4 on 2022-06-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_extracurricular_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extracurricular',
            old_name='duration',
            new_name='time',
        ),
    ]
